#!/bin/bash
# ∞ Meta

clear
#ACTUALIZADOR
[[ ! -e /etc/versin_script ]] && echo 1 > /etc/versin_script
v11=$(cat /etc/versin_script_new) 
v22=$(cat /etc/versin_script)
[[ $v11 = $v22 ]] && vesaoSCT="\033[1;32mVIP_PERU||Vers.$v22\033[1;97m✦҈͜͡➳👻𝕲𝔥𝔬𝔰𝔱•✓☆ۣۜۜ͜͡🌹 \033[1;31m]" || vesaoSCT="\033[1;32m$v22\033[1;32m \e[1;97m\e[0;103m\e[1;34m SCRIPT-MODS \033[0m" 
_hora=$(printf '%(%D-%H:%M:%S)T') 

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null 2>&1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null 2>&1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 > /dev/null 2>&1

#COLORES 
red=$(tput setaf 1)
gren=$(tput setaf 2)
yellow=$(tput setaf 3)

SCPdir="/etc/newadm" && [[ ! -d ${SCPdir} ]] && exit 1
SCPusr="${SCPdir}/ger-user" && [[ ! -d ${SCPusr} ]] && mkdir ${SCPusr}
SCPfrm="/etc/ger-frm" && [[ ! -d ${SCPfrm} ]] && mkdir ${SCPfrm}
SCPinst="/etc/ger-inst" && [[ ! -d ${SCPfrm} ]] && mkdir ${SCPfrm}
SCPidioma="${SCPdir}/idioma"

#PROCESSADOR
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")

#SISTEMA-USO DA CPU-MEMORIA RAM
ram1=$(free -h | grep -i mem | awk {'print $2'})
ram2=$(free -h | grep -i mem | awk {'print $4'})
ram3=$(free -h | grep -i mem | awk {'print $3'})

_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")

if [[ -e /etc/bash.bashrc-bakup ]]; then AutoRun="\033[1;32m[ON]"
elif [[ -e /etc/bash.bashrc ]]; then AutoRun="\033[1;31m[OFF]"
fi

cabec () {
clear
echo -e "\e[38m—————————————————————————————————————————————————————————\e[0m"
echo -e "\e[1;97;41m     ►► 👻 PANEL VIP•PERU 👻 ◄◄ | |   ✦҈͜͡➳👻𝕲𝔥𝔬𝔰𝔱•✓☆ۣۜۜ͜͡🌹       \e[0m"
echo -e "\e[38m—————————————————————————————————————————————————————————\e[0m"
tput sgr0
}

# Funcoes Globais
msg () {
local colors="/etc/new-adm-color"
if [[ ! -e $colors ]]; then
COLOR[0]='\033[1;37m' #BRAN='\033[1;37m'
COLOR[1]='\e[31m' #VERMELHO='\e[31m'
COLOR[2]='\e[32m' #VERDE='\e[32m'
COLOR[3]='\e[33m' #AMARELO='\e[33m'
COLOR[4]='\e[34m' #AZUL='\e[34m'
COLOR[5]='\e[91m' #MAGENTA='\e[35m'
COLOR[6]='\033[1;97m' #MAG='\033[1;36m'
else
local COL=0
for number in $(cat $colors); do
case $number in
1)COLOR[$COL]='\033[1;37m';;
2)COLOR[$COL]='\e[31m';;
3)COLOR[$COL]='\e[32m';;
4)COLOR[$COL]='\e[33m';;
5)COLOR[$COL]='\e[34m';;
6)COLOR[$COL]='\e[35m';;
7)COLOR[$COL]='\033[1;36m';;
esac
let COL++
done
fi
NEGRITO='\e[1m'
SEMCOR='\e[0m'
 case $1 in
  -ne)cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
  -ama)cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm)cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm2)cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -azu)cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verd)cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -bra)cor="${COLOR[0]}${SEMCOR}" && echo -e "${cor}${2}${SEMCOR}";;
  "-bar2"|"-bar")cor="${COLOR[1]}—————————————————————————————————————————————————————————" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
 esac
}
canbio_color () {
clear
cabec
msg -ama "   Cambiar Colores del Panel \033[1;31m[\033[1;32m VIP_PERU \033[1;31m]"
msg -bar2
msg -ama "$(fun_trans "Selecione 7 cores"): "
echo -e '\033[1;37m [1] ###\033[0m'
echo -e '\e[31m [2] ###\033[0m'
echo -e '\e[32m [3] ###\033[0m'
echo -e '\e[33m [4] ###\033[0m'
echo -e '\e[34m [5] ###\033[0m'
echo -e '\e[35m [6] ###\033[0m'
echo -e '\033[1;36m [7] ###\033[0m'
msg -bar2
for number in $(echo {1..7}); do
msg -ne "$(fun_trans "Digite un Color") [$number]: " && read corselect
[[ $corselect != @([1-7]) ]] && corselect=1
cores+="$corselect "
corselect=0
done
echo "$cores" > /etc/new-adm-color
msg -bar2
}

fun_trans () { 
local texto
local retorno
declare -A texto
SCPidioma="${SCPdir}/idioma"
[[ ! -e ${SCPidioma} ]] && touch ${SCPidioma}
local LINGUAGE=$(cat ${SCPidioma})
[[ -z $LINGUAGE ]] && LINGUAGE=es
[[ $LINGUAGE = "es" ]] && echo "$@" && return
[[ ! -e /usr/bin/trans ]] && wget -O /usr/bin/trans https://raw.githubusercontent.com/GM-VIP/SCRIPT/main/Install/trans &> /dev/null
[[ ! -e /etc/texto-adm ]] && touch /etc/texto-adm
source /etc/texto-adm
if [[ -z "$(echo ${texto[$@]})" ]]; then
retorno="$(source trans -e bing -b es:${LINGUAGE} "$@"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
echo "texto[$@]='$retorno'"  >> /etc/texto-adm
echo "$retorno"
else
echo "${texto[$@]}"
fi
}

atualiza_fun() {
tput clear && clear
    fun_ip
    SCPinstal="$HOME/install"
    verificar_arq() {
        case $1 in
        "menu"|"message.txt"|"menu.enc")ARQ="${SCPdir}/";; #Menu
        "usercodes")ARQ="${SCPusr}/";; #Panel SSRR
        "C-SSR.sh")ARQ="${SCPinst}/";; #Instalacao
        "openssh.sh")ARQ="${SCPinst}/";; #Instalacao
        "squid.sh")ARQ="${SCPinst}/";; #Instalacao
        "dropbear.sh")ARQ="${SCPinst}/";; #Instalacao
        "openvpn.sh")ARQ="${SCPinst}/";; #Instalacao
        "ssl.sh")ARQ="${SCPinst}/";; #Instalacao
        "sslorig.sh")ARQ="${SCPinst}/";; #Instalacao
        "shadowsocks.sh")ARQ="${SCPinst}/";; #Instalacao
        "Shadowsocks-libev.sh")ARQ="${SCPinst}/";; #Instalacao
        "Shadowsocks-R.sh")ARQ="${SCPinst}/";; #Instalacao 
        "v2ray.sh")ARQ="${SCPinst}/";; #Instalacao
        "budp.sh")ARQ="${SCPinst}/";; #Instalacao
        "sockspy.sh"|"PDirect.py"|"PPub.py"|"PPriv.py"|"POpen.py"|"PGet.py")ARQ="${SCPinst}/";; #Instalacao
        *) ARQ="${SCPfrm}/" ;;  #Ferramentas                                                                                          #Herramientas
        esac
        mv -f ${SCPinstal}/$1 ${ARQ}/$1
        chmod +x ${ARQ}/$1
    }
    error_fun() {
        msg -bar2 && msg -verm "ERROR entre VPS<-->GENERADOR (Port 81 TCP)" && msg -bar2
        [[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
        exit 1
    }
    invalid_key() {
        msg -bar2 && msg -verm "  Code Invalido -- #¡Key Invalida#! " && msg -bar2
        [[ -e $HOME/lista-arq ]] && rm -r $HOME/lista-arq
        exit 1
    }
     function_verify () {
  ### INTALAR VERCION DE SCRIPT
  v1=$(curl -sSL "https://raw.githubusercontent.com/GM-VIP/SCRIPT/main/VerScrpt/VercOld")
  echo "$v1" > /etc/versin_script
  [[ ! -e /usr/local/lib/lsystembin2 ]] && touch /usr/local/lib/lsystembin2
  }
    while [[ ! $Key ]]; do
        clear
        clear
        cabec
        echo -e "\033[1;91m          ACTUALIZAR FICHEROS DEL SCRIPT ∞ META"
        msg -bar2 && msg -ne "\033[1;96m             >>> INTRODUZCA LA KEY ABAJO <<<\n   \033[1;31m" && read Key
        tput cuu1 && tput dl1
    done
    msg -ne "    # Verificando Key # : "
    cd $HOME
    wget -O $HOME/lista-arq $(ofus "$Key")/$IP >/dev/null 2>&1 && echo -e "\033[1;32m Code Correcto de KEY" || {
        echo -e "\033[1;91m Code Incorrecto de KEY"
        invalid_key
        exit
    }
    IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$IP" >/usr/bin/vendor_code
    sleep 1s
    function_verify
    updatedb
    if [[ -e $HOME/lista-arq ]] && [[ ! $(cat $HOME/lista-arq | grep "Code de KEY Invalido!") ]]; then
        msg -bar2
        msg -verd "    $(source trans -b es:es "Ficheros Copiados" | sed -e 's/[^a-z -]//ig'): \e[97m[\e[93mVPS ∞ META\e[97m]"
        REQUEST=$(ofus "$Key" | cut -d'/' -f2)
        [[ ! -d ${SCPinstal} ]] && mkdir ${SCPinstal}
        pontos="."
        stopping="Configurando Directorios"
        for arqx in $(cat $HOME/lista-arq); do
            msg -verm "${stopping}${pontos}"
            wget --no-check-certificate -O ${SCPinstal}/${arqx} ${IP}:81/${REQUEST}/${arqx} >/dev/null 2>&1 && verificar_arq "${arqx}" || error_fun
            tput cuu1 && tput dl1
            pontos+="."
        done
        sleep 1s
        msg -bar2
        listaarqs="$(locate "lista-arq" | head -1)" && [[ -e ${listaarqs} ]] && rm $listaarqs
        cat /etc/bash.bashrc | grep -v '[[ $UID != 0 ]] && TMOUT=15 && export TMOUT' >/etc/bash.bashrc.2
        echo -e '[[ $UID != 0 ]] && TMOUT=15 && export TMOUT' >>/etc/bash.bashrc.2
        mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
        echo "${SCPdir}/menu" >/usr/bin/menu && chmod +x /usr/bin/menu
        echo "${SCPdir}/menu" >/usr/bin/Peru && chmod +x /usr/bin/Peru
        echo "$Key" >${SCPdir}/key.txt
        [[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
        rm -rf /root/lista-arq
        [[ ${#id} -gt 2 ]] && echo "es" >${SCPidioma} || echo "es" >${SCPidioma}
        echo -e "${cor[2]}                  ACTUALIZACION COMPLETA "
        echo -e "         COMANDO PRINCIPAL PARA ENTRAR AL PANEL:"
        echo -e "\033[0;37m                          \033[1;41m VIP \033[0m" && msg -bar2             
        rm -rf $HOME/lista-arq
    else
        invalid_key
    fi
    exit 1
}


funcao_idioma () {
tput cuu1 && tput dl1
msg -bar2
declare -A idioma=( [1]="en English" [2]="fr Franch" [3]="de German" [4]="it Italian" [5]="pl Polish" [6]="pt Portuguese" [7]="es Spanish" [8]="tr Turkish" )
for ((i=1; i<=12; i++)); do
valor1="$(echo ${idioma[$i]}|cut -d' ' -f2)"
[[ -z $valor1 ]] && break
valor1="\033[1;32m[$i] > \033[1;33m$valor1"
    while [[ ${#valor1} -lt 37 ]]; do
       valor1=$valor1" "
    done
echo -ne "$valor1"
let i++
valor2="$(echo ${idioma[$i]}|cut -d' ' -f2)"
[[ -z $valor2 ]] && {
   echo -e " "
   break
   }
valor2="\033[1;32m[$i] > \033[1;33m$valor2"
     while [[ ${#valor2} -lt 37 ]]; do
        valor2=$valor2" "
     done
echo -ne "$valor2"
let i++
valor3="$(echo ${idioma[$i]}|cut -d' ' -f2)"
[[ -z $valor3 ]] && {
   echo -e " "
   break
   }
valor3="\033[1;32m[$i] > \033[1;33m$valor3"
     while [[ ${#valor3} -lt 37 ]]; do
        valor3=$valor3" "
     done
echo -e "$valor3"
done
msg -bar2
unset selection
while [[ ${selection} != @([1-8]) ]]; do
echo -ne "\033[1;37m$(fun_trans "Selecione una Opcion"): " && read selection
tput cuu1 && tput dl1
done
[[ -e /etc/texto-adm ]] && rm /etc/texto-adm
echo "$(echo ${idioma[$selection]}|cut -d' ' -f1)" > ${SCPidioma}
}

mine_port () {
clear
cabec
echo -e "\033[1;93m      INFORMACION DEL SISTEMA Y PUERTOS ACTIVOS"
msg -bar2
echo -e "\033[1;31m PROCESADOR: \033[1;37mNUCLEOS: \033[1;32m$_core         \033[1;37mUSO DE CPU: \033[1;32m$_usop"
echo -e "\033[1;31m LA MEMORIA RAM SE ENCUENTRA AL: \033[1;32m$_usor"
echo -e "\033[1;31m DETALLE RAM: \033[1;37mTOTAL: \033[1;32m$ram1  \033[1;37mUSADO: \033[1;32m$ram3  \033[1;37mLIBRE: \033[1;32m$ram2"
msg -ne " SO: " && echo -ne "\033[1;37m$(os_system)  "
msg -ne " IP: " && echo -e "\033[1;37m$(meu_ip)"
msg -bar2
local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
local NOREPEAT
local reQ
local Port
while read port; do
reQ=$(echo ${port}|awk '{print $1}')
Port=$(echo {$port} | awk '{print $9}' | awk -F ":" '{print $2}')
[[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
NOREPEAT+="$Port\n"
case ${reQ} in
squid|squid3)
[[ -z $SQD ]] && local SQD="\033[1;31m SQUID: \033[1;32m"
SQD+="$Port ";;
apache|apache2)
[[ -z $APC ]] && local APC="\033[1;31m APACHE: \033[1;32m"
APC+="$Port ";;
ssh|sshd)
[[ -z $SSH ]] && local SSH="\033[1;31m SSH: \033[1;32m"
SSH+="$Port ";;
dropbear)
[[ -z $DPB ]] && local DPB="\033[1;31m DROPBEAR: \033[1;32m"
DPB+="$Port ";;
ssserver|ss-server)
[[ -z $SSV ]] && local SSV="\033[1;31m SHADOWSOCKS: \033[1;32m"
SSV+="$Port ";;
openvpn)
[[ -z $OVPN ]] && local OVPN="\033[1;31m OPENVPN-TCP: \033[1;32m"
OVPN+="$Port ";;
stunnel4|stunnel)
[[ -z $SSL ]] && local SSL="\033[1;31m SSL PREMIUM: \033[1;32m"
SSL+="$Port ";;
python|python3)
[[ -z $PY3 ]] && local PY3="\033[1;31m SOCKS/PYTHON: \033[1;32m"
PY3+="$Port ";;
v2ray)
[[ -z $V2R ]] && local V2R="\033[1;31m V2RAY: \033[1;32m"
V2R+="$Port ";;
badvpn-ud)
[[ -z $BAD ]] && local BAD="\033[1;31m BADVPN: \033[1;32m"
BAD+="$Port ";;
esac
done <<< "${portasVAR}"
#UDP
local portasVAR=$(lsof -V -i -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND")
local NOREPEAT
local reQ
local Port
while read port; do
reQ=$(echo ${port}|awk '{print $1}')
Port=$(echo ${port} | awk '{print $9}' | awk -F ":" '{print $2}')
[[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
NOREPEAT+="$Port\n"
case ${reQ} in
openvpn)
[[ -z $OVPN ]] && local OVPN="\033[0;36m OPENVPN-UDP: \033[1;32m"
OVPN+="$Port ";;
esac
done <<< "${portasVAR}"
[[ ! -z $SSH ]] && echo -e $SSH
[[ ! -z $SSL ]] && echo -e $SSL
[[ ! -z $WS ]] && echo -e $WS
[[ ! -z $DPB ]] && echo -e $DPB
[[ ! -z $SQD ]] && echo -e $SQD 
[[ ! -z $PY3 ]] && echo -e $PY3
[[ ! -z $SSV ]] && echo -e $SSV
[[ ! -z $V2R ]] && echo -e $V2R 
[[ ! -z $APC ]] && echo -e $APC
[[ ! -z $OVPN ]] && echo -e $OVPN
[[ ! -z $BAD ]] && echo -e $BAD
msg -bar2
}

ofus () {
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="*";;
"*")txt[$i]=".";;
"1")txt[$i]="@";;
"@")txt[$i]="1";;
"2")txt[$i]="?";;
"?")txt[$i]="2";;
"4")txt[$i]="%";;
"%")txt[$i]="4";;
"-")txt[$i]="K";;
"K")txt[$i]="-";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}

remove_ferramenta () {
echo -e "\033[1;31m$(fun_trans "ATENCION"): "
echo -e "\033[1;33m$(fun_trans "Este Proceso No Podra Ser Detenido")"
echo -e "\033[1;33m$(fun_trans "Selecione la Herramienta que Desea Remover")"
msg -bar2
Numb=0
for arqs in $(ls ${SCPfrm}); do
float_data "$arqs" "$Numb" && {
  script[$Numb]="$arqs"
  let Numb++
  }
done
echo -ne "$(msg -verd " [0]") $(msg -verm2 "=>>") " && msg -bra "$(fun_trans "  VOLVER")"
script[0]="voltar"
msg -bar2
selection=999
selection=$(selection_fun $Numb)
[[ -e "${SCPfrm}/${script[$selection]}" ]] && rm ${SCPfrm}/${script[$selection]} || return
}

agregar_ferramenta () {
tput cuu1 && tput dl1
msg -bar2
unset Key
echo -e "\033[1;31m$(fun_trans "ATENCION"): "
echo -e "\033[1;33m$(fun_trans "No introduzca una clave de actualizacion aqui")"
echo -e "\033[1;37m$(fun_trans "Introdusca una  clave para la nueva herramienta") "
msg -bar2
while [[ -z $Key ]]; do
echo -ne "[Key/Link]: " && read Key
tput cuu1 && tput dl1
done
echo -ne "\033[1;37m$(fun_trans "Verificando key"): "
cd ${SCPfrm}
curl "$Key" &> /dev/null
if [[ $? = "0" ]]; then
echo -e "\033[1;32m $(fun_trans "Link Valido")"
REC=$(echo $Key|awk -F"/" '{print $NF}')
echo -ne "\033[1;33m$(fun_trans "Recibendo Recurso"): \033[1;31m[$REC]"
wget -O ${SCPfrm}/${REC} $Key &>/dev/null && echo -e "\033[1;31m- \033[1;32m$(fun_trans "Recebido")" && chmod +x ${SCPfrm}/${REC} || echo -e "\033[1;31m- \033[1;31m$(fun_trans "Erro al Recibir")"
else
wget $(ofus "$Key") >/dev/null 2>&1 && echo -e "\033[1;32m $(fun_trans "Key Valida")" || {
    msg -verm "$(fun_trans "Key invalida")"
    msg -bar2
    return 0   
    }
fi
IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
sleep 1s
[[ -e ${SCPfrm}/lista-arq ]] && {
  if [[ $(cat ${SCPfrm}/lista-arq) = "KEY DE INSTALACION!" ]]; then
  echo -e "\033[1;33m$(fun_trans "KEY DE INSTALACION NO DEBE SER USADA AQUI")"
  msg -bar2
  rm ${SCPfrm}/lista-arq
  return 1
  fi
  if [[ $(cat ${SCPfrm}/lista-arq) = "KEY INVALIDA!" ]]; then
  echo -e "\033[1;33m$(fun_trans "KEY INVALIDA")"
  msg -bar2
  rm ${SCPfrm}/lista-arq
  return 1
  fi
  REQUEST=$(ofus "$Key" |cut -d'/' -f2)
  for arqx in $(cat ${SCPfrm}/lista-arq); do
  echo -ne "\033[1;33m$(fun_trans "Recibiendo Recurso"): \033[1;31m[$arqx] "
  wget -O ${SCPfrm}/${arqx} ${IP}:81/${REQUEST}/${arqx} > /dev/null 2>&1 && echo -e "\033[1;31m- \033[1;32m$(fun_trans "Recebido")" && chmod +x ${SCPfrm}/${arqx} || echo -e "\033[1;31m- \033[1;31m$(fun_trans "Erro al Recibir")"
  sleep 1s
  done
  rm ${SCPfrm}/lista-arq
  msg -bar2
  } 
}

limpar_caches () {
(
VE="\033[1;33m" && MA="\033[1;31m" && DE="\033[1;32m"
while [[ ! -e /tmp/abc ]]; do
A+="#"
echo -e "${VE}[${MA}${A}${VE}]" >&2
sleep 0.3s
tput cuu1 && tput dl1
done
echo -e "${VE}[${MA}${A}${VE}] - ${DE}[100%]" >&2
rm /tmp/abc
) &
echo 3 > /proc/sys/vm/drop_caches &>/dev/null
sleep 1s
sysctl -w vm.drop_caches=3 &>/dev/null
apt-get autoclean -y &>/dev/null
sleep 1s
apt-get clean -y &>/dev/null
rm /tmp/* &>/dev/null
touch /tmp/abc
sleep 0.5s
msg -bar
msg -ama "$(fun_trans "PROCESO CONCLUIDO")"
msg -bar
}

fun_autorun () {
if [[ -e /etc/bash.bashrc-bakup ]]; then
mv -f /etc/bash.bashrc-bakup /etc/bash.bashrc
cat /etc/bash.bashrc | grep -v "/etc/newadm/menu" > /tmp/bash
mv -f /tmp/bash /etc/bash.bashrc
msg -ama "$(fun_trans "REMOVIDO CON EXITO")"
msg -bar
elif [[ -e /etc/bash.bashrc ]]; then
cat /etc/bash.bashrc|grep -v /bin/adm > /etc/bash.bashrc.2
echo '/etc/newadm/menu' >> /etc/bash.bashrc.2
cp /etc/bash.bashrc /etc/bash.bashrc-bakup
mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
msg -ama "$(fun_trans "AUTO INICIALIZAR AGREGADO")"
msg -bar
fi
}

fun_bar () {
comando="$1"
 _=$(
$comando > /dev/null 2>&1
) & > /dev/null
pid=$!
while [[ -d /proc/$pid ]]; do
echo -ne " \033[1;33m["
   for((i=0; i<10; i++)); do
   echo -ne "\033[1;31m##"
   sleep 0.2
   done
echo -ne "\033[1;33m]"
sleep 1s
echo
tput cuu1
tput dl1
done
echo -e " \033[1;33m[\033[1;31m####################\033[1;33m] - \033[1;32m100%\033[0m"
sleep 1s
}

meu_ip () {
if [[ -e /etc/MEUIPADM ]]; then
echo "$(cat /etc/MEUIPADM)"
else
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
[[ "$MEU_IP2" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
echo "$MEU_IP2" > /etc/MEUIPADM
fi
}

fun_ip () {
if [[ -e /etc/MEUIPADM ]]; then
IP="$(cat /etc/MEUIPADM)"
else
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ifconfig.me)
[[ "$MEU_IP" != "$MEU_IP2" ]] && IP="$MEU_IP2" || IP="$MEU_IP"
echo "$MEU_IP2" > /etc/MEUIPADM
fi
}

fun_eth () {
eth=$(ifconfig | grep -v inet6 | grep -v lo | grep -v 127.0.0.1 | grep "encap:Ethernet" | awk '{print $1}')
    [[ $eth != "" ]] && {
    msg -bar
    msg -ama " $(fun_trans "Aplicar el sistema para mejorar los paquetes SSH?")"
    msg -ama " $(fun_trans "Opciones para usuarios avanzados")"
    msg -bar
    read -p " [S/N]: " -e -i n sshsn
           [[ "$sshsn" = @(s|S|y|Y) ]] && {
           echo -e "${cor[1]} $(fun_trans "Correccion de problemas de paquetes en SSH ...")"
           echo -e " $(fun_trans "¿Cual es la tasa RX?")"
           echo -ne "[ 1 - 999999999 ]: "; read rx
           [[ "$rx" = "" ]] && rx="999999999"
           echo -e " $(fun_trans "¿Cual es la tasa TX?")"
           echo -ne "[ 1 - 999999999 ]: "; read tx
           [[ "$tx" = "" ]] && tx="999999999"
           apt-get install ethtool -y > /dev/null 2>&1
           ethtool -G $eth rx $rx tx $tx > /dev/null 2>&1
           }
     msg -bar
     }
}

os_system () {
system=$(echo $(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //'))
echo $system|awk '{print $1, $2}'
}

remove_script () {
   clear
   cabec
   msg -ama "          ¿ DESEA DESINSTALAR SCRIPT ∞ META?"
   msg -bar
   echo -e "    Esto borrara todos los archivos del script ∞ Meta"
   msg -bar
   while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
      read -p " [S/N]: " yesno
      tput cuu1 && tput dl1
   done
   if [[ ${yesno} = @(s|S|y|Y) ]]; then
      rm -rf ${SCPdir} &>/dev/null
      rm -rf ${SCPusr} &>/dev/null
      rm -rf ${SCPinst} &>/dev/null
      [[ -e /bin/newadm ]] && rm /bin/newadm
      [[ -e /usr/bin/newadm ]] && rm /usr/bin/newadm
      [[ -e /bin/menu ]] && rm /bin/menu
      [[ -e /usr/bin/menu ]] && rm /usr/bin/menu
      cd $HOME
   fi
   sudo apt-get --purge remove squid -y >/dev/null 2>&1
   sudo apt-get --purge remove stunnel4 -y >/dev/null 2>&1
   sudo apt-get --purge remove dropbear -y >/dev/null 2>&1
mv .bashrc.backup .bashrc
sleep 1
sudo reboot
}
# Menu Ferramentas
systen_info () {
clear
cabec
msg -ama "$(fun_trans " DETALLES DEL SISTEMA")"
null="\033[1;31m"
msg -bar
if [ ! /proc/cpuinfo ]; then msg -verm "$(fun_trans "Sistema No Soportado")" && msg -bar; return 1; fi
if [ ! /etc/issue.net ]; then msg -verm "$(fun_trans "Sistema No Soportado")" && msg -bar; return 1; fi
if [ ! /proc/meminfo ]; then msg -verm "$(fun_trans "Sistema No Soportado")" && msg -bar; return 1; fi
totalram=$(free | grep Mem | awk '{print $2}')
usedram=$(free | grep Mem | awk '{print $3}')
freeram=$(free | grep Mem | awk '{print $4}')
swapram=$(cat /proc/meminfo | grep SwapTotal | awk '{print $2}')
system=$(cat /etc/issue.net)
clock=$(lscpu | grep "CPU MHz" | awk '{print $3}')
based=$(cat /etc/*release | grep ID_LIKE | awk -F "=" '{print $2}')
processor=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F ":" '{print $2}')
cpus=$(cat /proc/cpuinfo | grep processor | wc -l)
[[ "$system" ]] && msg -ama "$(fun_trans "Sistema"): ${null}$system" || msg -ama "$(fun_trans "Sistema"): ${null}???"
[[ "$based" ]] && msg -ama "$(fun_trans "Base"): ${null}$based" || msg -ama "$(fun_trans "Base"): ${null}???"
[[ "$processor" ]] && msg -ama "$(fun_trans "Procesador"): ${null}$processor x$cpus" || msg -ama "$(fun_trans "Procesador"): ${null}???"
[[ "$clock" ]] && msg -ama "$(fun_trans "Frecuencia de Operacion"): ${null}$clock MHz" || msg -ama "$(fun_trans "Frecuencia de Operacion"): ${null}???"
msg -ama "$(fun_trans "Uso del Procesador"): ${null}$(ps aux  | awk 'BEGIN { sum = 0 }  { sum += sprintf("%f",$3) }; END { printf " " "%.2f" "%%", sum}')"
msg -ama "$(fun_trans "Memoria Virtual Total"): ${null}$(($totalram / 1024))"
msg -ama "$(fun_trans "Memoria Virtual En Uso"): ${null}$(($usedram / 1024))"
msg -ama "$(fun_trans "Memoria Virtual Libre"): ${null}$(($freeram / 1024))"
msg -ama "$(fun_trans "Memoria Virtual Swap"): ${null}$(($swapram / 1024))MB"
msg -ama "$(fun_trans "Tempo Online"): ${null}$(uptime)"
msg -ama "$(fun_trans "Nombre De La Maquina"): ${null}$(hostname)"
msg -ama "$(fun_trans "IP De La  Maquina"): ${null}$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')"
msg -ama "$(fun_trans "Version de Kernel"): ${null}$(uname -r)"
msg -ama "$(fun_trans "Arquitectura"): ${null}$(uname -m)"
msg -bar
return 0
}

float_data () {
ofc="\033[0m${gren}(#OFICIAL)"
dev="\033[0m${yellow}(#BETA)"
dev2="\033[0m${red}(#PREMIUM)"

case $1 in
"paysnd.sh")return 1;;
"ultrahost")return 1;;
"speed.sh")return 1;;
"apacheon.sh")return 1;;
"ports.sh")return 1;;
"dns-netflix.sh")return 1;;
"tcp.sh")return 1;;
"gestor.sh")return 1;;
"Unlock-Pass-VULTR.sh")return 1;;
"squidpass.sh")return 1;;
"fai2ban.sh")return 1;;
"blockBT.sh")return 1;;
"utils.sh")return 1;;
"ADMbot.sh")return 1;;
"C-SSR.sh")return 1;;
"Crear-Demo.sh")return 1;;
"pwd.pwd")return 1;;
"PDirect.py")return 1;;
"PGet.py")return 1;;
"POpen.py")return 1;;
"PPriv.py")return 1;;
"PPub.py")return 1;;
"speedtest.py")return 1;;
"SSH20.log")return 1;; 
*)echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "${1^^} \033[1;33m($(fun_trans "No Hay Una Descripcion")!)";;
esac
}

aviso_bock () {
  echo 'echo -e "\033[1;91m==============================================================\n¡SCRIPT BLOQUEADO !\n=============================================================="' > /usr/bin/menu
  echo 'echo -e "\033[1;91m==============================================================\n¡SCRIPT BLOQUEADO !\n=============================================================="' > /usr/bin/adm
 rm -rf /etc/newadm
}

[[ ! -e $(echo -e $(echo "2f7573722f6c6f63616c2f6c69622f6c73797374656d62696e32"| sed 's/../\\x&/g;s/$/ /')) ]] && $( aviso_bock > /dev/null 2>&1)

ferramentas_fun () {
tput sgr0
clear
cabec
msg -ama "                 MENU DE HERRAMIENTAS"
msg -bar2
local Numb=1
for arqs in $(ls ${SCPfrm}); do
float_data "$arqs" "$Numb" && {
  script[$Numb]="$arqs"
  let Numb++
  }
done
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "ADMINISTAR BOT DE TELEGRAM  $ofc"
script[$Numb]="ADMbot.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "COMPARTIR ARCHIVO ONLINE            $ofc"
script[$Numb]="apacheon.sh"
echo -e "\033[1;93m-----------------------SEGURIDAD---------------------"
#PROTECION
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "FIREWALL VPS VPS•GHOST            $ofc"
script[$Numb]="blockBT.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "FAIL2BAN PROTECION                  $ofc"
script[$Numb]="fai2ban.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "AUTENTIFICAR PROXY SQUID            $ofc"
script[$Numb]="squidpass.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "DESACTIVAR PASS ALFANUMERICO        $ofc"
script[$Numb]="Unlock-Pass-VULTR.sh"
echo -e "\033[1;93m--------------------AJUSTES INTERNOS-----------------"
#AJUSTES INTERNOS
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "TCP ACELERACION (BBR/PLUS)          $dev"
script[$Numb]="tcp.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "AGREGAR DNS NETFLIX    $ofc"
script[$Numb]="dns-netflix.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "ADMINISTRAR PUERTOS ACTIVOS         $ofc"
script[$Numb]="ports.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "Pass Root/Add root/Horario/etc..   $ofc"
script[$Numb]="gestor.sh"
#OPTIMIZADORES
echo -e "\033[1;93m---------------------OPTIMIZADORES-------------------"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "Limpiar/Cache/Ram/Librerias/etc..  $ofc"
script[$Numb]="utils.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "DETALLES DE SISTEMA                $ofc"
script[$Numb]="systeminf"
#EXTRAS
echo -e "\033[1;93m-------------------------EXTRAS----------------------"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "PAYLOAD FUERZA BRUTA               $ofc"
script[$Numb]="paysnd.sh"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "SCANNER DE SUBDOMINIO              $ofc"
script[$Numb]="ultrahost"
let Numb++
echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "PRUEBA DE VELOCIDAD                $ofc"
script[$Numb]="speed.sh"
echo -ne "$(msg -verd "[0]") $(msg -verm2 ">") " && msg -bra "$(fun_trans "  VOLVER")"
script[0]="voltar"
msg -bar2
selection=$(selection_fun $Numb)
[[ -e "${SCPfrm}/${script[$selection]}" ]] && {
  ${SCPfrm}/${script[$selection]} 
  } || {
  case ${script[$selection]} in
  "limpar")limpar_caches;;
  "systeminf")systen_info;;
  *)return 0;;
  esac
  }  
}

pid_inst () {
[[ $1 = "" ]] && echo -e "\033[1;31m [◉] " && return 0
unset portas
portas_var=$(lsof -V -i -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND")
i=0
while read port; do
var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
[[ "$(echo -e ${portas[@]}|grep "$var1 $var2")" ]] || {
    portas[$i]="$var1 $var2\n"
    let i++
    }
done <<< "$portas_var"
[[ $(echo "${portas[@]}"|grep "$1") ]] && echo -e "\033[1;32m [◉] " || echo -e "\033[1;31m [◉] "
}

menu_inst () {
pid_inst
###PID BASICO
valuest=$(ps ax |grep /etc/shadowsocks-r|grep -v grep)
[[ $valuest != "" ]] && valuest="\033[1;32m [◉] \e[0m" || valuest="\033[1;31m [◉] \e[0m"
   export -f fun_eth
   export -f fun_bar
   tput sgr0
   clear
   cabec
   echo -e "        \e[1;47;30m         MENU DE PROTOCOLOS           \e[0m"
    echo -e "	\e[1;41;29m   GRUPO-1   \e[0m		 \e[1;41;29m   GRUPO-2   \e[0m"
    msg -bar
    echo -e "$(msg -verd "[1]") $(msg -azu "OPENSSH      ➭ $(pid_inst sshd)")   $(msg -verd "[7]") $(msg -azu "V2RAY        ➭ $(pid_inst v2ray)")"
    echo -e "$(msg -verd "[2]") $(msg -azu "DROPBEAR     ➭ $(pid_inst dropbear)")   $(msg -verd "[8]") $(msg -azu "SOCK-PYTHON  ➭ $(pid_inst python)")"
    echo -e "$(msg -verd "[3]") $(msg -azu "SQUID        ➭ $(pid_inst squid)")   $(msg -verd "[9]") $(msg -azu "SHADOWSOCK-N ➭ $(pid_inst ssserver)")"
    echo -e "$(msg -verd "[4]") $(msg -azu "OPENVPN      ➭ $(pid_inst openvpn)")   $(msg -verd "[10]")$(msg -azu "SHADOWSOCK-R ➭ ${valuest}")"
    echo -e "$(msg -verd "[5]") $(msg -azu "BAD-VPN 7300 ➭ $(pid_inst badvpn)")   $(msg -verd "[11]")$(msg -azu "SHADOWSOCK-L ➭ $(pid_inst ss-server)")"
    echo -e "$(msg -verd "[6]") $(msg -azu "SSL PREMIUM  ➭ $(pid_inst stunnel4)")   $(msg -verd "[12]")$(msg -azu "SSL REMASTER ➭ $(pid_inst stunnel4)")"
    echo -e "$(msg -verd "[0]") \033[1;41m| REGRESA A PANEL |\e[0m    $(msg -verd "[13]") \033[1;100m   TOOLS | EXTRAS  \e[0m"
    msg -bar
    echo -ne " ►\e[1;37m Selecione Una Opcion: \e[33m " && read select
    case $select in
    0) ;;

    1)
        ${SCPinst}/openssh.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    2)
        ${SCPinst}/dropbear.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    3)
        ${SCPinst}/squid.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    4)
        ${SCPinst}/openvpn.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    5)
        ${SCPinst}/budp.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    6)
        ${SCPinst}/ssl.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;                
    7)
        ${SCPinst}/v2ray.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    8)
        ${SCPinst}/sockspy.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    9)
        ${SCPinst}/shadowsocks.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    10)
        ${SCPinst}/Shadowsocks-R.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    11)
        ${SCPinst}/Shadowsocks-libev.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;
    12)
        ${SCPinst}/sslorig.sh && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;                 
    13)
        ferramentas_fun && msg -ne "Enter Para Continuar" && read enter
        menu_inst
        ;;                       
    *)
        msg -verm2 " OPCION INVALIDA, ESCOGE OTRAVEZ !!!"
        sleep 1.s
        menu_inst
        ;;
    esac
}

# MENU FLUTUANTE
menu_func () {
local options=${#@}
local array
for((num=1; num<=$options; num++)); do
echo -ne "  $(msg -verd "[$num]") $(msg -verm2 "=>>") "
  array=(${!num})
  case ${array[0]} in
    "-vd")msg -verd "\033[1;33m[!]\033[1;32m $(fun_trans "${array[@]:1}")" | sed ':a;N;$!ba;s/\n/ /g';;
    "-vm")msg -verm2 "\033[1;33m[!]\033[1;31m $(fun_trans "${array[@]:1}")" | sed ':a;N;$!ba;s/\n/ /g';;
    "-fi")msg -azu "$(fun_trans "${array[@]:2}") ${array[1]}" | sed ':a;N;$!ba;s/\n/ /g';;
    *)msg -azu "$(fun_trans "${array[@]}")" | sed ':a;N;$!ba;s/\n/ /g';;
  esac
done
}

# SISTEMA DE SELECAO
selection_fun () {
local selection="null"
local range
for((i=0; i<=$1; i++)); do range[$i]="$i "; done
while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
echo -ne "\033[1;37m$(fun_trans "Selecione una Opcion"): " >&2
read selection
tput cuu1 >&2 && tput dl1 >&2
done
echo $selection
}

# EXECUCION DE MENU
export -f msg
export -f selection_fun
export -f fun_trans
export -f  menu_func
export -f meu_ip
export -f fun_ip
clear

# resellers
resellers () {
clear
cabec
echo
echo -e "  \e[1;92m |>>>>>> PANEL RESELLER | VIP-GHOST <<<<<|\e[0m"
echo -e "\e[1;92m Por favor, digita a continuacion el nuevo RESELLER!!\e[0m"
read -p " RESELLER: " Ghost
echo "$Ghost" > /etc/newadm/message.txt
msg -bar2
echo
echo
msg -bra "            RESELLER:  "$Ghost
echo
msg -bar
echo "       ▪︎NUEVO CREDITO AGREDADO CON EXITO!!!"
msg -bar
echo '#!/bin/sh -e' > /etc/rc.local
sudo chmod +x /etc/rc.local
echo "sudo rebootnb" >> /etc/rc.local
echo "sudo resetsshdrop" >> /etc/rc.local
echo "sleep 2s" >> /etc/rc.local
echo "exit 0" >> /etc/rc.local
/bin/cp /etc/skel/.bashrc ~/
echo 'clear' >> .bashrc
echo 'DATE=$(date +"%d-%m-%y")' >> .bashrc
echo 'TIME=$(date +"%T")' >> .bashrc
sleep 1
return 0
clear
}

#SCRIPT PARA COMBINAR IP CON DOMINIO O SNI.
sni () {
clear
cabec
nums=$(seq 100 299 | tr -s '\n' '|')
nums+=$(seq -s"|" 400 499)
echo
echo -e "\e[01;33m 📂 MODULO UNIFICACIÓN IP + SNI . \e[0m \n\n\e[02m Función : \n Está herramienta sirve para combinar una IP + SNI ,\n esta función aturde a los  desencriptadores \n de métodos del netfree. \n\n ¿Cómo se usa? \n |   ➤ Pegar tu IP / Enter.\n ||  ➤ Pegar tu puerto habilitado ( Recomendado 443 ) /Enter.   \n ||| ➤ Pegar tu SNI , HOST o DOMINIO / Enter.      \n\n 
 Listo , escoja una  IP de la lista y pegue en donde se \n pone el SNI , HOST o DOMINIO. \e[0m\n"; sleep 1

while :; do
echo -e "\e[01;37m ➤ Pegar tu IP / Enter. \e[0m"
read -p " IP DE TU DROPLEP: " IP
echo -e "\e[01;37m ➤ PUERTO A USAR (Recomendado 442, 443, 444) /Enter.\e[0m"
read -p " PUERTO: " PORTA
echo -e "\e[01;37m ➤ Pegar tu SNI , HOST o DOMINIO / Enter. \e[0m"
read -p " HOST: " DOMINIO

dots=$(fgrep "." -o <<< $IP | wc -l)
> ips.txt; echo "@EhisOpeNer" > a; > b
case $dots in
  1) echo -e "\e[01;33m Cargando lista de IP convertidos a SNI disponibles ... \e[0m\n"; sleep 2
     #  Esperar carga ...
     ;;                                                    
  2) ips=$(for i in {0..255}; do echo $IP$i.; done)
      for i in {0..255}; do                             
         case $i in 0) i=1; esac                        
         ips2=$(sed -n "$i"p <<< "$ips");
            for i1 in {0..255}; do
                echo $ips2$i1 >> ips.txt
            done
      done
      echo -e "\n\e[01;33m Analizando lista de IP. \n Esto puede demorar. \e[0m\n\e[02m [Espere porfavor / error alguno vuelva a intentar proceso]\e[0m\n"
       x=$(($(wc -l < ips.txt)/3))

         $(for i in $(seq $x); do ip=$(sed -n "$i"p ips.txt); try=$(curl -m 3 -s -o /dev/null -w "%{http_code}" $DOMINIO -H "Upgrade: websocket" -x $ip:$PORTA); eval "case $try in $nums\ ) echo \"$ip|$try\" >> OK.txt; echo \"\e[01;33m$ip\e[0m | \e[01;37mIP OK - STATUS $try\e[0m\" >> ips2.txt; echo \"@EhisOpeNer\" >> a;; *):; esac"; done; echo a >> b) </dev/null >/dev/null 2>&1&

         $(for i in $(seq $(($x+1)) $(($x*2))); do ip=$(sed -n "$i"p ips.txt); try=$(curl -m 3 -s -o /dev/null -w "%{http_code}" $DOMINIO -H "Upgrade: websocket" -x $ip:$PORTA); eval "case $try in $nums\ ) echo \"$ip|$try\" >> OK.txt; echo \"\e[01;33m$ip\e[0m | \e[01;37mIP OK - STATUS $try\e[0m\" >> ips2.txt; echo \"@EhisOpeNer\" >> a;; *):; esac"; done; echo a >> b) </dev/null >/dev/null 2>&1&

         $(for i in $(seq $(($x*2+1)) $(wc -l < ips.txt)); do ip=$(sed -n "$i"p ips.txt); try=$(curl -m 3 -s -o /dev/null -w "%{http_code}" $DOMINIO -H "Upgrade: websocket" -x $ip:$PORTA); eval "case $try in $nums\ ) echo \"$ip|$try\" >> OK.txt; echo \"\e[01;33m$ip\e[0m | \e[01;37mIP OK - STATUS $try\e[0m\" >> ips2.txt; echo \"@EhisOpeNer\" >> a;; *):; esac"; done; echo a >> b) </dev/null >/dev/null 2>&1&
      
      while :; do
       linhas=$(wc -l < a)
         case $linhas in
              1) echo -e "\e[01;33m Cargando  lista  de IP ...\e[0m"| pv -qL 10; sleep 2; tput cuu1; tput dl1;
                 linhas=$(wc -l < b)
                  case $linhas in
                      3) echo -e "\e[01;37m IP no encontrado... \e[0m"| pv -qL 10; sleep 1; break
                  esac;;
              *) linhas=$(wc -l < b)
                  case $linhas in
                      3) break;
                  esac
                 echo -e "\e[01;37m IP Disponibles en carga \e[0m"| pv -qL 10; sleep 2; tput cuu1; tput dl1;;
         esac
      done

      linhas=$(wc -l < a)
        case $linhas in
             1) echo -e "\e[01;33m IP NO ENCONTRADO... $IP\255.255\e[0m"; break;;
             *) linhas=$(wc -l < b)
                OK=$(<ips2.txt)
                echo -e "$OK"; break
         esac
     ;;
  3) for i in {0..255}; do echo $IP$i >> ips.txt; done
      for i in $(seq $(wc -l < ips.txt)); do
         ip=$(sed -n "$i"p ips.txt)
         try=$(curl -m 3 -s -o /dev/null -w "%{http_code}" $DOMINIO -H "Upgrade: websocket" -x $ip:$PORTA)
          eval "case $try in
                 $nums\ )
                      echo -e \"\e[01;33m$ip\e[0m | \e[01;37mIP OK - STATUS $try\e[0m\"
                      echo \"$ip|$try\" >> OK.txt;;
                   *)
                      echo -e \"$ip | \e[01;33mSTATUS $try\e[0m\"
           esac"
      done; echo ================= >> OK.txt; break
     ;;
  *) echo -e "\e[01;31m ➭ ERROR FORMATO INCORRECTO.    \e[0m\n"; sleep 1
esac
done; rm ips.txt ips2.txt b a 2> /dev/n
}

cambiopass () {
clear
cabec
echo
echo -e "${cor[3]} $(fun_trans "Esta herramienta cambia la contraseña de su servidor VPS")"
echo -e "${cor[3]} $(fun_trans "Esta contraseña es utilizada como usuario") root"
msg -bar
echo -ne " $(fun_trans "Desea Seguir?") [S/N]: "; read x
[[ $x = @(n|N) ]] && msg -bar && return
msg -bar
#Inicia Procedimentos
echo -e "${cor[0]} $(fun_trans "Escriba su nueva contraseña")"
msg -bar
read  -p " Nuevo passwd: " pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
msg -bar
echo -e "${cor[3]} $(fun_trans "Contraseña cambiada con exito!")"
echo -e "${cor[2]} $(fun_trans "Su contraseña ahora es"): ${cor[4]}$pass"
msg -bar
return
}

#MONITOR DE SERVICIOS
monservi_fun () {
clear
monssh () {
sed -i "57d" /bin/monitor.sh
sed -i '57i EstadoServicio ssh' /bin/monitor.sh
}
mondropbear () {
sed -i "59d" /bin/monitor.sh
sed -i '59i EstadoServicio dropbear' /bin/monitor.sh
}
monssl() {
sed -i "61d" /bin/monitor.sh
sed -i '61i EstadoServicio stunnel4' /bin/monitor.sh
}
monsquid() {
sed -i "63d" /bin/monitor.sh
sed -i '63i [[ $(EstadoServicio squid) ]] && EstadoServicio squid3' /bin/monitor.sh
}
monapache() {
sed -i "65d" /bin/monitor.sh
sed -i '65i EstadoServicio apache2' /bin/monitor.sh
}

clear
cabec
echo -e "\033[1;32m          MONITOR DE SERVICIOS PRINCIPALES"
msg -bar
PIDVRF3="$(ps aux|grep "${SCPdir}/menu monitorservi"|grep -v grep|awk '{print $2}')"

PIDVRF5="$(ps aux|grep "${SCPdir}/menu moni2"|grep -v grep|awk '{print $2}')"

if [[ -z $PIDVRF3 ]]; then
sed -i '5a\screen -dmS very3 /etc/newadm/menu monitorservi' /bin/resetsshdrop
msg -bar
echo -e "\033[1;34m          ¿Monitorear Protocolo SSH/SSHD?"
msg -bar
read -p "                    [ s | n ]: " monssh  
sed -i "57d" /bin/monitor.sh
sed -i '57i #EstadoServicio ssh' /bin/monitor.sh 
[[ "$monssh" = "s" || "$monssh" = "S" ]] && monssh
msg -bar
echo -e "\033[1;34m          ¿Monitorear Protocolo DROPBEAR?"
msg -bar
read -p "                    [ s | n ]: " mondropbear  
sed -i "59d" /bin/monitor.sh
sed -i '59i #EstadoServicio dropbear' /bin/monitor.sh
[[ "$mondropbear" = "s" || "$mondropbear" = "S" ]] && mondropbear
msg -bar
echo -e "\033[1;34m            ¿Monitorear Protocolo SSL?"
msg -bar
read -p "                    [ s | n ]: " monssl  
sed -i "61d" /bin/monitor.sh
sed -i '61i #EstadoServicio stunnel4' /bin/monitor.sh
[[ "$monssl" = "s" || "$monssl" = "S" ]] && monssl
msg -bar
echo -e "\033[1;34m            ¿Monitorear Protocolo SQUID?"
msg -bar
read -p "                    [ s | n ]: " monsquid  
sed -i "63d" /bin/monitor.sh
sed -i '63i #[[ $(EstadoServicio squid) ]] && EstadoServicio squid3' /bin/monitor.sh
[[ "$monsquid" = "s" || "$monsquid" = "S" ]] && monsquid
msg -bar
echo -e "\033[1;34m            ¿Monitorear Protocolo APACHE?"
msg -bar
read -p "                    [ s | n ]: " monapache  
sed -i "65d" /bin/monitor.sh
sed -i '65i #EstadoServicio apache2' /bin/monitor.sh
[[ "$monapache" = "s" || "$monapache" = "S" ]] && monapache

#echo "screen -dmS very3 /etc/newadm/menu monitorservi" >> /bin/resetsshdrop
cd ${SCPdir}
screen -dmS very3 ${SCPdir}/menu monitorservi
screen -dmS monis2 ${SCPdir}/menu moni2
else

for pid in $(echo $PIDVRF3); do
kill -9 $pid &>/dev/null
sed -i "6d" /bin/resetsshdrop
done

for pid in $(echo $PIDVRF5); do
kill -9 $pid &>/dev/null
done

fi
msg -bar
echo -e "             Puedes Monitorear desde:\n       \033[1;32m http://$(meu_ip):81/monitor.html"
msg -bar
[[ -z ${VERY3} ]] && monitorservi="\033[1;32m ACTIVADO " || monitorservi="\033[1;31m DESACTIVADO "
echo -e "            $monitorservi  --  CON EXITO"
msg -bar
}

#TIMER MONITOR
monitor_auto () {
while true; do
monitor.sh 2>/dev/null
sleep 120s 
    done
}
if [[ "$1" = "monitorservi" ]]; then
monitor_auto
exit
fi
#RESET PYDIREC
pid_kill () {
[[ -z $1 ]] && refurn 1
pids="$@"
for pid in $(echo $pids); do
kill -9 $pid &>/dev/null
done
}

monitorport_fun () {
while true; do
pidproxy3=$(ps x | grep "PDirect.py" | grep -v "grep" | awk -F "pts" '{print $1}') && [[ ! -z $pidproxy3 ]] && pid_kill $pidproxy3
sleep 6h 
done
}
if [[ "$1" = "moni2" ]]; then
monitorport_fun
exit
fi

# CREDITOS
creditoss () {
clear 
cabec
echo
echo -ne " \033[1;93m      🔰OWNER : GHOST [CREDITOS-INFORMACION] \n"
msg -bar
[[ -e ${SCPdir}/message.txt ]] && msg -bra " 👤 RESELLER AUTORIZADO : \033[1;96m $(cat ${SCPdir}/message.txt) "
[[ -e ${SCPdir}/key.txt ]] && msg -bra " KEY DE REGISTRO VPS•GHOST :\n \033[1;93m $(cat ${SCPdir}/key.txt)"
msg -bar
echo -ne "\033[1;97m   🔰MAQUINA VIRTUAL🔰:     \n"
echo -ne "➳ EN CONSTANTE ACTUALIZACIONES.      \n"
echo -ne "➳ DISEÑOS Y RENOVACION UNICOS VPS•PERU.   ㅤ\n"
echo -ne "➳ TELEGRAM BOT GEN•KEY PREMIUM : @VIP_GENKEY_BOT     \n"
echo -ne "➳ ✨VIP•GHOST✨    \n"
echo -ne "➳ ACCESO PREMIUM A TU ADMINISTRACION DE PANEL.     \n"
echo -ne "➳ TEN EN CUENTA EN CONFIGURAR CORRECTAMENTE LOS :    \n"
echo -ne "➳ INSTALADORES DE PROTOCOLOS PREMIUM.       \n"
echo -ne "➳ DISFRUTE DE SU VPS•PERU Y GRACIAS POR CONTAR CON NOSOTROS.   \n"
echo -ne "➳ 🔰[ADMINISTRATOR]🔰 : 🐲[GHOST]🐲           \n"
echo -ne "➳ 🔰PARTNES : [LATINOAMERICA] ✓ [✦҈͜͡➳👻𝕲𝔥𝔬𝔰𝔱•✓☆ۣۜۜ͜͡🌹]           \n"
echo -ne "➳ PORFAVOR CUALQUIER ERROR DE LA SCRIPT CONTACTAR VIA TELEGRAM CON:          \n"
echo -ne "➳ @GENKEY_BOT       \n"
msg -bar
}

### VISOR DE CLIMA
climat () {
clear; clear
tput cup 10 0
figlet -p -f smslant "WEATHER_VISOR" | lolcat
link1 () {
echo
curl wttr.in/$locac?m
}
link2 () {
echo
curl wttr.in/$locac?0 --silent --max-time 3
}
sleep 2
clear
cabec
echo; echo -e "\e[1;47;31m    ☆☆☆ PRONOSTICO DEL CLIMA PERSONALIZADO ☆☆☆    \e[0m"
echo -ne "\e[1;32m ℹ CIUDAD A VERIFICAR EL CLIMA: \e[0m" && read locac
msg -bar
echo -e "\e[1;31m[1] \e[1;33m VISTA MODO SIMPLE\e[0m"
echo -e "\e[1;31m[2] \e[1;33m VISTA MODO COMPLETO\e[0m"
msg -bar
selection=$(selection_fun 2)
case ${selection} in
1)link2;;
2)link1;;
esac
}

panel_reg () {
# PANEL REGISTROS
clear
cabec
msg -bra "\033[1;32m             REGISTROS DE USUARIOS         \e[0m"
msg -bar
echo -e "\e[1;97m SSH/SSL[$(pid_inst stunnel4)\e[1;97m] OPVPN[$(pid_inst openvpn)\e[1;97m] SS/SSR[$(pid_inst python)\e[1;97m] V2RAY[$(pid_inst v2ray)\e[1;97m]\e[0m"

#CUENTAS REGISTRAADAS APROX
SSHN="$(grep -c home /etc/passwd)"
SSH2="$(echo ${SSHN}|bc)-1"
echo "${SSH2}"|bc > /etc/newadm/ger-user/SSH20.log
SSH3="$(less /etc/newadm/ger-user/SSH20.log)"
SSH4="$(echo $SSH3)"

#MONITOR DE CUENTAS ACTIVAS SSRR
user_info=$(cd /usr/local/shadowsocksr &> /dev/null  && python mujson_mgr.py -l ) 
user_total=$(echo "${user_info}"|wc -l)
on="\033[1;92m[ON]\e[0m" && off="\033[1;31m[OFF]\e[0m"

Bot=$(ps x|grep -v grep |grep "ADMbot.sh") 
[[ ! $Bot ]] && AD="\033[1;31m[OFF]\e[0m" || AD="\033[1;32m[ON]\e[0m" 
[[ $(ps x | grep badvpn | grep -v grep | awk '{print $1}') ]] && badvpn=$on || badvpn=$off
on="\e[1;32m[ON]\e[0m" && off="\e[1;31m[OFF]\e[0m"

VERY="$(ps aux|grep "${SCPusr}/usercodes verificar"| grep -v grep)"
VERY2="$(ps aux|grep "${SCPusr}/usercodes desbloqueo"| grep -v grep)"
VERY3="$(ps aux|grep "${SCPdir}/menu monitorservi"| grep -v grep)"
limseg="$(less /etc/newadm/ger-user/tiemlim.log)" 
[[ -z ${VERY} ]] && verificar="\033[1;31m[OFF]" || verificar="\033[1;32m[ON]"
[[ -z ${VERY2} ]] && desbloqueo="\033[1;31m[OFF]" || desbloqueo="\033[1;32m[ON]"
[[ -z ${VERY3} ]] && monitorservi="\033[1;31m[OFF]" || monitorservi="\033[1;32m[ON]"

[[ -e ${SCPdir}/USRonlines ]] && msg -bar && msg -ne "\033[1;97m   LIMITADOR:\033[1;92m $verificar \033[1;97m DESBLOQUEO AUTOMATICO:\033[1;92m $desbloqueo\n   \033[1;32mCONECTADOS: " && echo -ne "\033[1;97m$(cat ${SCPdir}/USRonlines) "
[[ -e ${SCPdir}/USRexpired ]] && msg -ne "   EXPIRADOS: " && echo -ne "\033[1;97m$(cat ${SCPdir}/USRexpired) "  && msg -ne " \033[1;95m BLOQUEADOS: " && echo -e "\033[1;97m$(cat ${SCPdir}/USRbloqueados) \n\033[1;97m        ACTUALIZA MONITOR CADA: \033[1;34m $limseg s" 

msg -bar
echo -e "\e[1;32m[1] \e[97mREGISTRO || (SSH/SSL/DROP/OPVPN/WS) \e[1;31mCount: \033[1;92m$SSH4\e[0m"
echo -e "\e[1;32m[2] \e[97mREGISTRO || (SS/SSR SHADOWSOCK)     \e[1;31mCount: \033[1;92m$user_total\e[0m"
echo -e "\e[1;32m[3] \e[97mREGISTRO || (X-RAY/V2RAY) \e[0m"  
msg -bar
echo -e "\e[1;32m[0] \e[97mREGRESAR AL PANEL \e[0m" 
msg -bar
selection=$(selection_fun 4)
case ${selection} in
1)${SCPusr}/usercodes "${idioma}" ;;
2)${SCPinst}/C-SSR.sh ;;
3)${SCPinst}/v2ray.sh ;;
0)return;;
*)
esac
}

menu_adc () {
clear
cabec
echo -e "\033[1;32m                MENU ADICIONAL         \e[0m"
msg -bar
echo -ne "$(msg -verd "[1]") "&& msg -bra "\033[1;97m➪ CAMBIAR COLORES DEL PANEL   "
echo -ne "$(msg -verd "[2]") "&& msg -bra "\033[1;97m➪ RENOVAR RESELLER   "
echo -ne "$(msg -verd "[3]") "&& msg -bra "\033[1;97m➪ MODIFICAR CONTRASEÑA ROOT   "
echo -ne "$(msg -verd "[4]") "&& msg -bra "\033[1;97m➪ UNIFICAR IP + SNI   "
echo -ne "$(msg -verd "[5]") "&& msg -bra "\033[1;97m➪ MONITOR HTOP 1.0   "
echo -ne "$(msg -verd "[6]") "&& msg -bra "\033[1;97m➪ BOT DE GESTIÓN - TELEGRAM $AD   "
echo -ne "$(msg -verd "[7]") "&& msg -bra "\033[1;97m➪ CREDITOS DEL SCRIPT   "
echo -ne "$(msg -verd "[8]") "&& msg -bra "\033[1;97m➪ CLIMATOLOGIA (BETA)   "
msg -bar
echo -ne "$(msg -verd "[0]") "&& msg -bra "\033[1;31m➪ REGRESAR AL PANEL   "
msg -bar
selection=$(selection_fun 9)
case ${selection} in
1)canbio_color;;
2)resellers;;
3)cambiopass;;
4)sni;;
5)monhtop;;
6)${SCPfrm}/ADMbot.sh;;
7)creditoss;;
8)climat;;
0)return;;
*)
esac
}

monhtop () {
clear 
cabec
echo -ne " \033[1;93m             MONITOR DE PROCESOS HTOP\e[0m"
msg -bar
msg -bra "    RECUERDA SALIR CON : \033[1;96m CTRL + C o FIN + F10 "
[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || apt-get install htop -y &>/dev/null
msg -bar
read -t 10 -n 1 -rsp $'\033[1;39m Preciona Enter Para continuar\n'
clear
sudo htop
cabec
echo -ne " \033[1;93m             MONITOR DE PROCESOS HTOP\n"
msg -bar
echo -e "\e[97m                  FIN DEL MONITOR"
msg -bar
}

# VISUALIZACION DE MENU

VERY3="$(ps aux|grep "${SCPdir}/menu monitorservi"| grep -v grep)"
[[ -z ${VERY3} ]] && monitorservi="\033[1;31m[OFF]" || monitorservi="\033[1;32m[ON]"
Bot=$(ps x|grep -v grep |grep "ADMbot.sh") 
[[ ! $Bot ]] && AD="\033[1;31m[OFF]" || AD="\033[1;32m[ON] " 
on="\e[1;32m[ON]" && off="\e[1;31m[OFF]"

echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
echo -e "\e[97m\033[1;41m 📋PANEL DE CONTROL VIP_PERU   | |   ✦҈͜͡➳👻𝕲𝔥𝔬𝔰𝔱•✓☆ۣۜۜ͜͡🌹   \e[0m"
echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
msg -bra " \e[1;34m OFC Vers: \033[1;32m$vesaoSCT\033[1;97m"
echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
[[ -e ${SCPdir}/message.txt ]] && msg -bra " \e[1;34m👤 RESELLER:  \e[1;33m[$(cat ${SCPdir}/message.txt)]"
echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
msg -ne "     S.O: " && echo -ne "\033[1;37m$(os_system)"
msg -ne "     IP: " && echo -e "\033[1;37m$(meu_ip)\e[0m"
echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
echo -e "\e[1;32m[1] \e[97mREGISTROS (SSH/SSL/DROP/OPVPN/WS/SS-SSR/V2RAY)\e[0m"
echo -e "\e[1;32m[2] \e[97mPROTOCOLOS  ||  \e[47;1;30mHERRAMIENTAS\e[0m"
echo -e "\e[1;32m[3] \e[97mPUERTOS ACTIVADOS \e[0m"
echo -e "\e[1;32m[4] \e[97mMENU ADICIONAL \e[0m ▪︎ \e[1;33mBADVPN:$(pid_inst badvpn)\e[0m"
echo -e "\e[1;32m[5] \e[97mMONITOR  >>>>>>︎|${monitorservi} \e[0m"
echo -e "\e[1;32m[6] \e[97mAUTO_INICIO >>>|$AutoRun \e[0m"
echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
echo -e "\e[1;32m[7] \e[1;32mACTUALIZAR\e[0m  \e[1;32m[8] \e[1;31mDESINTALAR\e[0m  \e[1;32m[0] \e[47;31m CERRAR PANEL \e[0m"
echo -e "\e[1;97m—————————————————————————————————————————————————————\e[0m"
selection=$(selection_fun 9)
case ${selection} in
1)panel_reg;;
2)menu_inst;;
3)mine_port;;
4)menu_adc;;
5)monservi_fun;;
6)fun_autorun;;
7)atualiza_fun;;
8)remove_script;;
0)clear && cd $HOME && exit 0;;
*)
esac
msg -ne "Enter Para Continuar" && read enter
${SCPdir}/menu
#fin
########
